config/routes.rb
Blog1::Application.routes.draw do
  resources :tags

  # resources :comments
  resources :articles do
    resources :comments
  end

  devise_for :users

  root 'articles#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :content, presence: true
  # validates_associated :user
  validates :user_id, presence: true

  def user_email
    self.user.email
  end
  def user_name
    self.user.name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @comment = Comment.new(comment_params)
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        # format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.html { redirect_to article_path(@article), notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        # UserMailer.notif_comment(@comment.article.user.email, @comment).deliver
        UserMailer.delay.notif_comment(@comment.article.user.email, @comment)
      else
        # format.html { render action: 'new' }
        format.html { render 'articles/show' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        # format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.html { redirect_to article_path(@article), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      # format.html { redirect_to comments_url }
      format.html { redirect_to article_path(@article) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_article
      @article = Article.find(params[:article_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :article_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<!--%= form_for(@comment) do |f| %-->
<%= form_for(@comment, url: params[:action].to_s == 'edit' ? article_comment_path(@comment.article, @comment) : article_comments_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', article_comment_path(@comment.article, @comment) %> |
<%= link_to 'Back', article_comments_path %>

<!--%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %-->

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Article</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.article_id %></td>
        <td><%= link_to 'Show', article_comment(comment) %></td>
        <td><%= link_to 'Edit', '' %></td>
        <td><%= link_to 'Destroy', '', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <!--td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', '' %>
<!--%= link_to 'New Comment', new_comment_path %-->

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Edit', edit_article_comment_path(@comment.article, @comment) %> |
<%= link_to 'Back', article_path(@comment.article) %>

<!--%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %-->