config/routes.rb
Blog1::Application.routes.draw do
  resources :tags

  # resources :comments
  resources :articles do
    resources :comments
  end

  devise_for :users

  root 'articles#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :tags
  mount_uploader :image, ImageUploader

  validates :name, :content, presence: true
  ## validates_associated :users
  # validates :image, presence: true
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.all
    @articles = Article.order("name").page(params[:page]).per(2)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    # @article = Article.new(article_params)
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :content, :user_id, :image, {:tag_ids => []})
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => {:multipart => true} do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, label: 'Title', input_html: {maxlength: 20} %>
  <%= f.input :content %>
  <%= image_tag(@article.image_url) if @article.image? %>
  <%= f.input :image %>
  <%= f.association :tags, as: :check_boxes %>
  <div class="form-actions">
    <%= f.button :submit, "Submit" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Author</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.content %></td>
        <td><%= article.user.name %></td>
        <td>
          <% article.tags.each do |tag| %>
            <%= tag.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @articles %>
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= image_tag(@article.image_url) if @article.image? %>
  <%= @article.content %>
</p>

<p>
  <%= image_tag @article.image.url(:mini) if @article.image? %>
  <%= image_tag @article.image.thumbnail.url if @article.image? %>
  <%= image_tag @article.image.medium.url if @article.image? %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.user.name %>
</p>

<% if can? :update, @article %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', articles_path %>
<h2>Comment</h2>
<ul>
  <% @article.comments.each do |comment| %>
    <li>
      <p><%= comment.content %></p>
      <p>By: <%= comment.user_name %></p>
      <% if can? :update, comment %>
        <%= link_to 'Edit comment', edit_article_comment_path(@article, comment) %> |
      <% end %>
      <% if can? :destroy, comment %>
        <%= link_to 'Destroy Comment', [comment.article, comment],
          :confirm => 'Are you sure?',
          :method => :delete %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= simple_form_for([@article, @comment]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit, "Submit" %>
<% end %>